services:
  # Traefik - Edge Reverse Proxy
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"  # Enable the dashboard but only on port 9080
      - "--api.dashboard=true"  # Enable the dashboard
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--entrypoints.web.address=:80"
      # SSE Connections need long timeouts
      - "--entrypoints.web.transport.respondingTimeouts.idleTimeout=300s"
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=300s"
      - "--entrypoints.web.transport.respondingTimeouts.writeTimeout=300s"
      # Enable debug logging
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard port mapped to same port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/config:/etc/traefik/config"
    networks:
      - mcp-network
    labels:
      - "traefik.enable=true"
      # Dashboard only on port 9080, not on the main domain
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=traefik"

  # GitHub MCP Server with SuperGateway
  github-gateway:
    image: node:18
    container_name: github-gateway
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "npm install -g supergateway && 
             supergateway --port 8000 --baseUrl /github --stdio 'npx -y @modelcontextprotocol/server-github'"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - mcp-network
    labels:
      - "traefik.enable=true"
      # GitHub MCP server configuration
      - "traefik.http.routers.github.rule=Host(`${MCP_HOST:-mcpserver.localhost}`) && PathPrefix(`/github`)"
      - "traefik.http.routers.github.entrypoints=web"
      - "traefik.http.services.github.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.github-strip.stripprefix.prefixes=/github"
      - "traefik.http.routers.github.middlewares=github-strip"

  # Notion MCP Server with SuperGateway
  notion-gateway:
    image: node:18
    container_name: notion-gateway
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "npm install -g supergateway && 
             supergateway --port 8000 --baseUrl /notion --stdio 'npx -y @orbit-logistics/notion-mcp-server -t ${NOTION_API_TOKEN}'"
    environment:
      - NOTION_API_TOKEN=${NOTION_API_TOKEN}
    networks:
      - mcp-network
    labels:
      - "traefik.enable=true"
      # Notion MCP server configuration
      - "traefik.http.routers.notion.rule=Host(`${MCP_HOST:-mcpserver.localhost}`) && PathPrefix(`/notion`)"
      - "traefik.http.routers.notion.entrypoints=web"
      - "traefik.http.services.notion.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.notion-strip.stripprefix.prefixes=/notion"
      - "traefik.http.routers.notion.middlewares=notion-strip"

networks:
  mcp-network:
    name: mcp-network 
