# Each mcp server is going to be prefixed with a comment with the following:
# Name of server, language, package path

services:
  # Traefik MCP proxy
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    command:
      # Base config + enable dashboard
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--entrypoints.web.address=:80"
      # SSE Connections stay alive like websockets- set to infinity
      - "--entrypoints.web.transport.respondingTimeouts.idleTimeout=0"
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=0"
      - "--entrypoints.web.transport.respondingTimeouts.writeTimeout=0"
    ports:
      - "9080:80"
      - "8080:8080"  # Dashboard port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/config:/etc/traefik/config"
    networks:
      - mcp-network
    labels:
      - "traefik.enable=true"
      # Dashboard only on port 8080, not on the main domain
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=traefik"
    profiles:
      - github
      - notion
      - memory-bank
      - linear
      - fetch
      - all

networks:
  mcp-network:
    name: mcp-network

# Include service-specific compose files
include:
  - docker-compose/github.yml
  - docker-compose/notion.yml
  - docker-compose/memory-bank.yml
  - docker-compose/linear.yml 
  - docker-compose/fetch.yml
