services:
  # Linear, node, smithery@tiovikram/linear-mcp
  linear-gateway:
    image: node:18
    container_name: linear-gateway
    restart: unless-stopped
    working_dir: /app
    command: /app/entrypoint.sh
    volumes:
      - ../scripts/linear-entrypoint.sh:/app/entrypoint.sh:rx
    environment:
      - LINEAR_ACCESS_TOKEN=${LINEAR_API_KEY}
    networks:
      - mcp-network
    labels:
      - "traefik.enable=true"
      # linear MCP server configuration
      - "traefik.http.routers.linear.rule=Host(`${MCP_HOST:-mcpserver.localhost}`) && PathPrefix(`/linear`)"
      - "traefik.http.routers.linear.entrypoints=web"
      - "traefik.http.services.linear.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.linear-strip.stripprefix.prefixes=/linear"
      - "traefik.http.routers.linear.middlewares=linear-strip"
    profiles:
      - linear
      - all

# Networks are defined in the main docker-compose.yml file 