services:
  # Memory bank, node, @allpepper/memory-bank-mcp
  memory-bank-gateway:
    image: node:18
    container_name: memory-bank
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ${MEMORY_BANK_ROOT}:/bank:rw
    command: >
      sh -c "npm install -g supergateway &&
             supergateway --port 8000 --baseUrl /memory-bank --stdio 'npx -y @allpepper/memory-bank-mcp'"
    environment:
      - MEMORY_BANK_ROOT=${MEMORY_BANK_ROOT}
    networks:
      - mcp-network
    labels:
      - "traefik.enable=true"
      # memory-bank MCP server configuration
      - "traefik.http.routers.memory-bank.rule=Host(`${MCP_HOST:-mcpserver.localhost}`) && PathPrefix(`/memory-bank`)"
      - "traefik.http.routers.memory-bank.entrypoints=web"
      - "traefik.http.services.memory-bank.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.memory-bank-strip.stripprefix.prefixes=/memory-bank"
      - "traefik.http.routers.memory-bank.middlewares=memory-bank-strip"
    profiles:
      - memory-bank
      - all

# Networks are defined in the main docker-compose.yml file 