http:
  middlewares:
    
    # SSE timeouts middleware
    sseTimeouts:
      buffering:
        maxResponseBodyBytes: 0
        memResponseBodyBytes: 0
        maxRequestBodyBytes: 0
        memRequestBodyBytes: 0
        retryExpression: ""
   
    # Content Type middleware
    contentType:
      contentType:
        autoDetect: true
    
    # CORS middleware for MCP servers
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - OPTIONS
        accessControlAllowHeaders:
          - "Content-Type"
          - "Origin"
          - "Accept"
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 100
        addVaryHeader: true
    
    # Strip prefix middleware for Notion MCP server
    notion-strip:
      stripPrefix:
        prefixes:
          - "/notion"
    
    # Strip prefix middleware for GitHub MCP server
    github-strip:
      stripPrefix:
        prefixes:
          - "/github"
    
    # Strip prefix middleware for memory bank
    memory-bank-strip:
      stripPrefix:
        prefixes:
          - "/memory-bank"

    # Strip prefix middleware for linear
    linear-strip:
      stripPrefix:
        prefixes:
          - "/linear"

    # Strip prefix middleware for dashboard
    dashboard-strip:
      stripPrefix:
        prefixes:
          - "/dashboard"

  # Add serversTransport configuration for ping timeout
  serversTransports:
    default:
      forwardingTimeouts:
        pingTimeout: 5s 
